cicd updated

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Build and Deploy to Dockerhub
+name: Build and Deploy to Docker Hub
 
 on:
   push:
@@ -7,10 +7,9 @@ on:
     paths-ignore:
       - '**.github/workflows/**' # Ignore changes to workflow files
     if: "contains(github.event.head_commit.message, '[deploy]')"
-
+    
 jobs:
   build-and-push:
-    if: "contains(github.event.head_commit.message, '[deploy]')"
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -18,6 +17,8 @@ jobs:
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
+        with:
+          install: true
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
@@ -42,12 +43,12 @@ jobs:
 
       - name: Build and push multi-architecture image
         run: |
-          echo "Building multi-architecture image for amd64, arm64, and windows/amd64..."
-          docker buildx build --platform linux/amd64,linux/arm64,windows/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/mdv-frontend:${{ env.NEW_VERSION }} --push .
-
-      - name: Tag and push latest version
-        run: |
-          echo "Tagging and pushing latest version..."
+          echo "Building multi-architecture image for linux/amd64, linux/arm64, and windows/amd64..."
+          if ! docker buildx build --platform linux/amd64,linux/arm64,windows/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/mdv-frontend:${{ env.NEW_VERSION }} --push .; then
+            echo "Error: Failed to build and push the Docker image."
+            exit 1
+          fi
+          # Tag the image with the latest tag as well
           docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/mdv-frontend:${{ env.NEW_VERSION }} ${{ secrets.DOCKER_HUB_USERNAME }}/mdv-frontend:latest
           docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mdv-frontend:latest
 
